name: Julia CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'  # Specify the Julia version

      - name: Install dependencies
        run: |
          julia --project=@. -e 'using Pkg; Pkg.instantiate()'
          julia --project=@. -e 'using Pkg; Pkg.add("Test")'

      - name: Run tests
        run: |
          julia --project=@. -e 'using Pkg; Pkg.test()'
